#!/bin/bash

DEST='./src'
MYLOVE='./mylove.ini'

function validate() {
    if [[ ! $1 ]]; then
        return 1
    elif [[ ! -f $1 && ! -d $1 ]]; then
        echo -e "$1: no such directory!"
        return 2
    fi
    return 0
}

while read LINE
do
    validate $LINE
    if [[ $? == 0 ]]; then
        echo -e "start to cp $LINE..."
        cp -r $LINE $DEST
    fi
done < $MYLOVE

echo -e "complete!"
